parameters:
#    merch_goods.example.class: Merch\GoodsBundle\Example

services:
#    merch_goods.example:
#        class: %merch_goods.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
