parameters:
#    merch_goods.example.class: Merch\GoodsBundle\Example

services:
    goods_user_registration.form.type:
        class: Merch\GoodsBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: goods_user_registration }
#    merch_goods.example:
#        class: %merch_goods.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
